# Generated by Django 3.1.2 on 2020-11-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=25)),
                ('Direccion', models.CharField(max_length=35)),
                ('Nit', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.DateTimeField(auto_now=True)),
                ('Facturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facturacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Numero', models.CharField(max_length=15)),
                ('Fecha', models.DateField()),
                ('CVV', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zapatoss', models.CharField(choices=[('A', 'Adidas'), ('N', 'Nike'), ('Z', 'Zapato')], default='J', max_length=1)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarjeta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Zapato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zapato'),
        ),
    ]
