# Generated by Django 3.1.2 on 2020-11-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201118_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Facturacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Tarjeta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Zapato',
        ),
        migrations.DeleteModel(
            name='Facturacion',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
        migrations.DeleteModel(
            name='Zapato',
        ),
    ]
